version: 1.2
workflows:
  - subclass: GALAXY
    primaryDescriptorPath: /Galaxy-ML2-LORIS_model.ga
    topic: LORIS model (Chang et al., 2024) Reproducibility using Galaxy-ML tools
    authors:
      - name: Paulo Lyra-Jr
        email: paulocilas.moraislyra@moffitt.org
